# Generated by Django 3.1.7 on 2021-05-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
    ]
